# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialPortTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Open_Com = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Com.setGeometry(QtCore.QRect(710, 490, 75, 41))
        self.Open_Com.setObjectName("Open_Com")
        self.Date_Display = QtWidgets.QTextEdit(self.centralwidget)
        self.Date_Display.setGeometry(QtCore.QRect(10, 30, 781, 371))
        self.Date_Display.setObjectName("Date_Display")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 410, 71, 16))
        self.label_2.setObjectName("label_2")
        self.Send_Data_Dsiplay = QtWidgets.QTextEdit(self.centralwidget)
        self.Send_Data_Dsiplay.setGeometry(QtCore.QRect(10, 430, 601, 111))
        self.Send_Data_Dsiplay.setObjectName("Send_Data_Dsiplay")
        self.Com_Port = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Port.setGeometry(QtCore.QRect(690, 430, 91, 22))
        self.Com_Port.setObjectName("Com_Port")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 430, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(630, 460, 41, 16))
        self.label_4.setObjectName("label_4")
        self.Com_Band = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Band.setGeometry(QtCore.QRect(690, 460, 91, 22))
        self.Com_Band.setObjectName("Com_Band")
        self.Send_Data = QtWidgets.QPushButton(self.centralwidget)
        self.Send_Data.setGeometry(QtCore.QRect(620, 490, 75, 41))
        self.Send_Data.setObjectName("Send_Data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Open_Com.clicked.connect(MainWindow.Open_Com_Click)
        self.Send_Data.clicked.connect(MainWindow.Send_Data_Click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Port Tools"))
        self.Open_Com.setText(_translate("MainWindow", "打开串口"))
        self.label.setText(_translate("MainWindow", "数据显示"))
        self.label_2.setText(_translate("MainWindow", "数据发送框"))
        self.label_3.setText(_translate("MainWindow", "串口号"))
        self.label_4.setText(_translate("MainWindow", "波特率"))
        self.Send_Data.setText(_translate("MainWindow", "发送数据"))
